name: 'hifigan_config2'
resblock: "1"

upsample_rates: [8,8,4]
upsample_kernel_sizes: [16,16,8]
upsample_initial_channel: 256
resblock_kernel_sizes: [3,5,7]
resblock_dilation_sizes: [[1,2], [2,6], [3,12]]

learning_rate: 0.0002
adam_b1: 0.8
adam_b2: 0.99
lr_decay: 0.999
